name: Deploy de la imagen de nginx

# Se define el trigger para la action. 
# Cuando se haga un push a master y se 
# haya modificado el index.html que se
# encuentra dentro de test-3, se 
# buildea una nueva imagen y se sube a ECR.
on:
  push:
    branches: [ master ]
    paths:
      - test-3/index.html
  # pull_request:
  #   branches: [ master ]
  #   types: [ closed ]
  #   paths:
  #     - test-3/index.html

jobs:
  deploy:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    # Se define el directorio donde se ejecuta la action.
    defaults:
      run:
        working-directory: test-3

    steps:

      # Se verifica el repositorio de github.
      - name: Checkout
        uses: actions/checkout@v3

      # Se configuran las credenciales de AWS requeridas para 
      # la autorización de ECR.
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Se inicia sesión en Amazon ECR.
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      # Se indica el nombre del repositorio y se corren los comandos
      # para crear la nueva imagen y pushearla a ECR.
      - name: Build, tag, and push docker image to Amazon ECR Public
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: ${{ secrets.ECR_ALIAS }}
          REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: my-image:latest
        run: |
          docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
          aws ecs update-service --cluster ${{ secrets.CLUSTER_NAME }} --force-new-deployment
